### ISSUE TITLE
decide on path for EDeN installation

### ISSUE THREAD

**Issue by dmaticzka** [fabriziocosta/EDeN#56]
We should add documentation on how to properly install EDeN. In order to do that we need to decide what installation system to support.

Currently, the test environment for travis.ci uses a mix of miniconda and pip. Miniconda uses precompiled packages which allows us to run installation and tests in less than two minutes.

Using pip alone will compile lots of stuff and would take about 20 minutes. We don't have a receipe that does that yet. Also, the installation of dependencies is error prone. @bgruening: I saw your EDeN Dockerfile, nice work! However, this currently fails with some compilation, I think it was scipy. These compilation issues were one reason I tried miniconda...

I used EDeN as an example for learning how to build docker images, appended is the latest version that installs EDeN including all dependencies and that passes all of the 4 :) tests we currently have. This uses a mix of Miniconda and pip.

So here's some points we should discuss:
- Should we have a single way to install EDeN and use that for our docker image, the travis tests and the installation instructions for the documentation. This will simplify maintenance in the long run.
- Another possible simplification: we could switch travis.ci to run the tests in our docker image. This will also give us more control over the testing environment.
- Should we continue to use Miniconda or put some effort into making things run exclusively with pip?
  - A possible plus for Miniconda would be that the packages come with the (system-level) libraries. (Thinking about the issue with ATLAS, BLAS and the latest Fedora...)

[Dockerfile.txt](https://github.com/fabriziocosta/EDeN/files/49538/Dockerfile.txt)

**Comment by bgruening** [comment]
The Docker image should be fixed, thanks for reporting. This happens again because we did not fixed all dependencies.

I like anaconda, but the default python package manager is pip and will be pip for the foreseeable future. So we should take care of supporting it. Actually @fabriziocosta should upload EDeN at some point to pypi.

Not sure if we *need* to support conda, it can not hurt. If we need it to save compile time and use it for testing we should somehow also test pip installation. We can use the Docker image for it the Galaxy Docker Image is using already Docker for testing, obviously. But then you are not testing the latest image or if you do it takes again 20min. Not sure if testing time should be an argument ...

**Comment by tzk** [comment]
Sure, testing time is not a good argument for using conda in builds. But
it's a benefit. On the other hand, the conda system still uses pip.
Overall, that's quite ugly.

If we want (or have) to support pip, I agree, we should also test for that.
Actually, when we use the travis.ci docker environment for building the
image for testing we might be able to cache the intermediate image
containing the dependencies. In that case we pay the compilation penalty
only when we actually change the dependencies. Eventually we might even use
docker-compose to test multiple versions, but let's concentrate on the
immediate.

In any case we need to fix versions. This is usually done by requesting
specific versions in a requirements.txt file. @fabriziocosta, we best start
with the versions you have installed since that's what most of the code was
developed against. You can get the currently installed versions via "pip
freeze" but you'll have to select the ones specifically required for eden.
(There we can also fix a specific commit of the pymf package we need to
install from the github repository.) Then we can immediately use it for
installing the dependecies in the docker image.

Any opinions about what to do about the setup.py install_requires?

PS: +1 for listing dependencies in alphabetic order :)





On Thu, Dec 3, 2015 at 11:01 PM, Björn Grüning <notifications@github.com>
wrote:

> The Docker image should be fixed, thanks for reporting. This happens again
> because we did not fixed all dependencies.
>
> I like anaconda, but the default python package manager is pip and will be
> pip for the foreseeable future. So we should take care of supporting it.
> Actually @fabriziocosta <https://github.com/fabriziocosta> should upload
> EDeN at some point to pypi.
>
> Not sure if we *need* to support conda, it can not hurt. If we need it to
> save compile time and use it for testing we should somehow also test pip
> installation. We can use the Docker image for it the Galaxy Docker Image is
> using already Docker for testing, obviously. But then you are not testing
> the latest image or if you do it takes again 20min. Not sure if testing
> time should be an argument ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabriziocosta/EDeN/issues/56#issuecomment-161798640>.
>



-- 
--------------------------------------------------
Daniel Maticzka, Dipl. Inf.
Lehrstuhl für Bioinformatik
Institut für Informatik
Albert-Ludwigs-Universität Freiburg

Tel: (+49) 761 203 97529
Fax: (+49) 761 203 7462
Mail: maticzkd@informatik.uni-freiburg.de
--------------------------------------------------
